sudo: true
language: node_js
node_js:
- '4.0'
env:
  global:
  - PRODUCTION_BRANCH=master
cache:
  directories:
  - "$HOME/docker"
services:
- docker
before_install:
- chmod +x ./.build_scripts/build.sh
- chmod +x ./.build_scripts/deploy.sh
after_success:
- ".build_scripts/build.sh"
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: ${PRODUCTION_BRANCH}
